return {
	PlaceObj('ModItemCode', {
		'name', "AssignEquipment",
		'CodeFileName', "Code/AssignEquipment.lua",
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_SMG",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"Suppressor",
				"ReflexSight",
				"LaserDot",
			},
			weapon = "MP5K",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_9mm_Subsonic",
			stack_max = 150,
			stack_min = 150,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_AssaultRifle",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"LaserDot",
				"AK47_VerticalGrip",
			},
			weapon = "AK47",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_762WP_Basic",
			stack_max = 40,
			stack_min = 150,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_MachineGun",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"Bipod",
			},
			weapon = "RPK74",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_762WP_Tracer",
			stack_max = 300,
			stack_min = 300,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_Shotgun",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"DuckbillChoke",
			},
			weapon = "Auto5",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_12gauge_Buckshot",
			stack_max = 120,
			stack_min = 120,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_SniperRifle",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"Suppressor",
			},
			weapon = "M24Sniper",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_762NATO_Match",
			stack_max = 40,
			stack_min = 40,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_MainGun_DualPistols",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"Suppressor",
				"LaserDot",
			},
			weapon = "Bereta92",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_9mm_Basic",
			stack_max = 150,
			stack_min = 150,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Sidearm_Pistol",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"ReflexSight",
				"Suppressor",
				"LaserDot",
			},
			weapon = "Bereta92",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_9mm_AP",
			stack_max = 80,
			stack_min = 80,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Sidearm_Revolver",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"BarrelLong",
			},
			weapon = "ColtAnaconda",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_44CAL_Shock",
			stack_max = 60,
			stack_min = 60,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Sidearm_MachinePistol",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			upgrades = {
				"Suppressor",
			},
			weapon = "Glock18",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "_9mm_Basic",
			stack_max = 150,
			stack_min = 150,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Armor_Light",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "FlakVest_WeavePadding",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "LightHelmet_WeavePadding",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "FlakLeggings_WeavePadding",
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Armor_Heavy",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "KevlarVest_CeramicPlates",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "KevlarHelmet",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "KevlarLeggings",
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Armor_Camo",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "CamoArmor_Light",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "NightVisionGoggles",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "FlakLeggings",
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Throwables_FragGrenades",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "FragGrenade",
			stack_max = 4,
			stack_min = 2,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Throwables_GlowSticks",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "GlowStick",
			stack_max = 20,
			stack_min = 12,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Throwables_SmokeGrenades",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "SmokeGrenade",
			stack_max = 8,
			stack_min = 4,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Throwables_TeargasGrenades",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "TearGasGrenade",
			stack_max = 6,
			stack_min = 3,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Throwables_MolotovCocktails",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "Molotov",
			stack_max = 4,
			stack_min = 2,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Extra_FlareGun",
		loot = "all",
		PlaceObj('LootEntryUpgradedWeapon', {
			weapon = "FlareHandgun",
		}),
		PlaceObj('LootEntryInventoryItem', {
			item = "FlareAmmo",
			stack_max = 15,
			stack_min = 8,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Extra_FirstAidKit",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "FirstAidKit",
			stack_max = 2,
			stack_min = 1,
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Extra_Lockpicks",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "Lockpick",
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Extra_WireCutter",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "Wirecutter",
		}),
	}),
	PlaceObj('ModItemLootDef', {
		group = "IMP",
		id = "MOG__ImpishEquipment__Item_Extra_Crowbar",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			item = "Crowbar",
		}),
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_F1",
		'comment', "IMP Equipment: Gun, for the 1st female IMP",
		'DisplayName', "<color 199 166 155>Female 1: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_F1",
		'comment', "IMP Equipment: Sidearm, for the 1st female IMP",
		'DisplayName', "<color 199 166 155>Female 1: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_F1",
		'comment', "IMP Equipment: Armor, for the 1st female IMP",
		'DisplayName', "<color 199 166 155>Female 1: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_F1",
		'comment', "IMP Equipment: Throwables, for the 1st female IMP",
		'DisplayName', "<color 199 166 155>Female 1: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_F1",
		'comment', "IMP Equipment: Extra, for the 1st female IMP",
		'DisplayName', "<color 199 166 155>Female 1: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_F2",
		'comment', "IMP Equipment: Gun, for the 2nd female IMP",
		'DisplayName', "<color 155 177 155>Female 2: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_F2",
		'comment', "IMP Equipment: Sidearm, for the 2nd female IMP",
		'DisplayName', "<color 155 177 155>Female 2: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_F2",
		'comment', "IMP Equipment: Armor, for the 2nd female IMP",
		'DisplayName', "<color 155 177 155>Female 2: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_F2",
		'comment', "IMP Equipment: Throwables, for the 2nd female IMP",
		'DisplayName', "<color 155 177 155>Female 2: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_F2",
		'comment', "IMP Equipment: Extra, for the 2nd female IMP",
		'DisplayName', "<color 155 177 155>Female 2: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_F3",
		'comment', "IMP Equipment: Gun, for the 3rd female IMP",
		'DisplayName', "<color 144 166 188>Female 3: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_F3",
		'comment', "IMP Equipment: Sidearm, for the 3rd female IMP",
		'DisplayName', "<color 144 166 188>Female 3: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_F3",
		'comment', "IMP Equipment: Armor, for the 3rd female IMP",
		'DisplayName', "<color 144 166 188>Female 3: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_F3",
		'comment', "IMP Equipment: Throwables, for the 3rd female IMP",
		'DisplayName', "<color 144 166 188>Female 3: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_F3",
		'comment', "IMP Equipment: Extra, for the 3rd female IMP",
		'DisplayName', "<color 144 166 188>Female 3: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_M1",
		'comment', "IMP Equipment: Gun, for the 1st male IMP",
		'DisplayName', "<color 199 166 155>Male 1: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_M1",
		'comment', "IMP Equipment: Sidearm, for the 1st male IMP",
		'DisplayName', "<color 199 166 155>Male 1: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_M1",
		'comment', "IMP Equipment: Armor, for the 1st male IMP",
		'DisplayName', "<color 199 166 155>Male 1: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_M1",
		'comment', "IMP Equipment: Throwables, for the 1st male IMP",
		'DisplayName', "<color 199 166 155>Male 1: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_M1",
		'comment', "IMP Equipment: Extra, for the 1st male IMP",
		'DisplayName', "<color 199 166 155>Male 1: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_M2",
		'comment', "IMP Equipment: Gun, for the 2nd male IMP",
		'DisplayName', "<color 155 177 155>Male 2: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_M2",
		'comment', "IMP Equipment: Sidearm, for the 2nd male IMP",
		'DisplayName', "<color 155 177 155>Male 2: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_M2",
		'comment', "IMP Equipment: Armor, for the 2nd male IMP",
		'DisplayName', "<color 155 177 155>Male 2: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_M2",
		'comment', "IMP Equipment: Throwables, for the 2nd male IMP",
		'DisplayName', "<color 155 177 155>Male 2: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_M2",
		'comment', "IMP Equipment: Extra, for the 2nd male IMP",
		'DisplayName', "<color 155 177 155>Male 2: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_MainGun_M3",
		'comment', "IMP Equipment: Gun, for the 3rd male IMP",
		'DisplayName', "<color 144 166 188>Male 3: Gun</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"SMG",
			"Assault Rifle",
			"Machine Gun",
			"Grenade Launcher",
			"Shotgun",
			"Sniper Rifle",
			"Dual Pistols",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Sidearm_M3",
		'comment', "IMP Equipment: Sidearm, for the 3rd male IMP",
		'DisplayName', "<color 144 166 188>Male 3: Sidearm</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Pistol",
			"Revolver",
			"Machine Pistol",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Armor_M3",
		'comment', "IMP Equipment: Armor, for the 3rd male IMP",
		'DisplayName', "<color 144 166 188>Male 3: Armor</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Light",
			"Heavy",
			"Camo",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Throwables_M3",
		'comment', "IMP Equipment: Throwables, for the 3rd male IMP",
		'DisplayName', "<color 144 166 188>Male 3: Throwables</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Frag Grenades",
			"Glow Sticks",
			"Smoke Grenades",
			"Tear Gas",
			"Molotov Cocktails",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "MOG__ImpishEquipment__Option_Extra_M3",
		'comment', "IMP Equipment: Extra, for the 3rd male IMP",
		'DisplayName', "<color 144 166 188>Male 3: Extra</color>",
		'DefaultValue', "-",
		'ChoiceList', {
			"-",
			"Flare Gun",
			"First Aid Kit",
			"Lockpicks",
			"Wire Cutter",
			"Crowbar",
		},
	}),
}
